[build]
  builder = "DOCKERFILE"

[deploy]
  startCommand = "bash start.sh"
  healthcheckPath = "/v1/query"
  healthcheckTimeout = 600
  restartPolicyType = "ON_FAILURE"
  restartPolicyMaxRetries = 20
