[build]
  builder = "DOCKERFILE"

[deploy]
  startCommand = "bash start.sh"
  healthcheckPath = "/readyz"
  healthcheckTimeout = 300
  restartPolicyType = "ON_FAILURE"
  restartPolicyMaxRetries = 10

[service]
  internalPort = 8080
